version: "3.10"
services:
   worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BANNED_USERS: $BANNED_USERS
      CHUNK_SIZE: $CHUNK_SIZE
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      UPDATE_CHANNEL: $UPDATE_CHANNEL
      WEBHOOK: $WEBHOOK
